export const AGREEMENT_REASON_CODES = {
  TERMS_PENDING: 'AGREEMENT_TERMS_PENDING',
  COUNTERPARTY_UNRESPONSIVE: 'AGREEMENT_COUNTERPARTY_UNRESPONSIVE',
  AWARD_PENDING: 'AGREEMENT_AWARD_PENDING',
} as const

export type AgreementReasonCode =
  (typeof AGREEMENT_REASON_CODES)[keyof typeof AGREEMENT_REASON_CODES]
