export const AGREEMENT_REASON_CODES = {
  SCORE_SUMMARY: 'AGREEMENT_SCORE_SUMMARY',
  STATUS_DRAFT: 'AGREEMENT_STATUS_DRAFT',
  STATUS_REVIEW: 'AGREEMENT_STATUS_REVIEW',
  STATUS_SIGNING: 'AGREEMENT_STATUS_SIGNING',
  STATUS_EXECUTING: 'AGREEMENT_STATUS_EXECUTING',
  STATUS_COMPLETED: 'AGREEMENT_STATUS_COMPLETED',
  STATUS_CANCELLED: 'AGREEMENT_STATUS_CANCELLED',
  TERMS_PENDING: 'AGREEMENT_TERMS_PENDING',
  REVIEW_INCOMPLETE: 'AGREEMENT_REVIEW_INCOMPLETE',
  SIGNATURES_PENDING: 'AGREEMENT_SIGNATURES_PENDING',
  STAGE_GATE_BLOCKED: 'AGREEMENT_STAGE_GATE_BLOCKED',
  CONTRACT_MISSING: 'AGREEMENT_CONTRACT_MISSING',
  COUNTERPARTY_UNRESPONSIVE: 'AGREEMENT_COUNTERPARTY_UNRESPONSIVE',
  AWARD_PENDING: 'AGREEMENT_AWARD_PENDING',
} as const

export type AgreementReasonCode =
  (typeof AGREEMENT_REASON_CODES)[keyof typeof AGREEMENT_REASON_CODES]
