export const ANALYTICS_REASON_CODES = {
  DATA_INSUFFICIENT: 'ANALYTICS_DATA_INSUFFICIENT',
  TREND_NEGATIVE: 'ANALYTICS_TREND_NEGATIVE',
  FORECAST_LOW_CONFIDENCE: 'ANALYTICS_FORECAST_LOW_CONFIDENCE',
} as const

export type AnalyticsReasonCode =
  (typeof ANALYTICS_REASON_CODES)[keyof typeof ANALYTICS_REASON_CODES]
