export const COMMERCIAL_REASON_CODES = {
  APPROVAL_PENDING: 'COMMERCIAL_APPROVAL_PENDING',
  DECISION_PENDING: 'COMMERCIAL_DECISION_PENDING',
  PAYMENT_PENDING: 'COMMERCIAL_PAYMENT_PENDING',
  VAT_VALIDATION_REQUIRED: 'COMMERCIAL_VAT_VALIDATION_REQUIRED',
  AWARD_PENDING: 'COMMERCIAL_AWARD_PENDING',
  STAGE_GATE_BLOCKED: 'COMMERCIAL_STAGE_GATE_BLOCKED',
} as const

export type CommercialReasonCode =
  (typeof COMMERCIAL_REASON_CODES)[keyof typeof COMMERCIAL_REASON_CODES]
