export const COMMERCIAL_REASON_CODES = {
  APPROVAL_PENDING: 'COMMERCIAL_APPROVAL_PENDING',
  PAYMENT_PENDING: 'COMMERCIAL_PAYMENT_PENDING',
  VAT_VALIDATION_REQUIRED: 'COMMERCIAL_VAT_VALIDATION_REQUIRED',
} as const

export type CommercialReasonCode =
  (typeof COMMERCIAL_REASON_CODES)[keyof typeof COMMERCIAL_REASON_CODES]
