export const CONTRACT_REASON_CODES = {
  SCORE_SUMMARY: 'CONTRACT_SCORE_SUMMARY',
  STATUS_DRAFT: 'CONTRACT_STATUS_DRAFT',
  STATUS_PENDING_SIGNATURE: 'CONTRACT_STATUS_PENDING_SIGNATURE',
  STATUS_ACTIVE: 'CONTRACT_STATUS_ACTIVE',
  STATUS_COMPLETED: 'CONTRACT_STATUS_COMPLETED',
  STATUS_TERMINATED: 'CONTRACT_STATUS_TERMINATED',
  SIGNATURE_PENDING: 'CONTRACT_SIGNATURE_PENDING',
  SIGNATURES_INCOMPLETE: 'CONTRACT_SIGNATURES_INCOMPLETE',
  ACTIVATION_PENDING: 'CONTRACT_ACTIVATION_PENDING',
  COMPLETION_READY: 'CONTRACT_COMPLETION_READY',
  TERMINATION_AVAILABLE: 'CONTRACT_TERMINATION_AVAILABLE',
  TERMS_UNRESOLVED: 'CONTRACT_TERMS_UNRESOLVED',
  MILESTONE_BLOCKED: 'CONTRACT_MILESTONE_BLOCKED',
} as const

export type ContractReasonCode =
  (typeof CONTRACT_REASON_CODES)[keyof typeof CONTRACT_REASON_CODES]
