export const CONTRACT_REASON_CODES = {
  SIGNATURE_PENDING: 'CONTRACT_SIGNATURE_PENDING',
  TERMS_UNRESOLVED: 'CONTRACT_TERMS_UNRESOLVED',
  MILESTONE_BLOCKED: 'CONTRACT_MILESTONE_BLOCKED',
} as const

export type ContractReasonCode =
  (typeof CONTRACT_REASON_CODES)[keyof typeof CONTRACT_REASON_CODES]
