export const DASHBOARD_REASON_CODES = {
  ACTION_REQUIRED: 'DASHBOARD_ACTION_REQUIRED',
  PIPELINE_STALLED: 'DASHBOARD_PIPELINE_STALLED',
  DEADLINE_APPROACHING: 'DASHBOARD_DEADLINE_APPROACHING',
} as const

export type DashboardReasonCode =
  (typeof DASHBOARD_REASON_CODES)[keyof typeof DASHBOARD_REASON_CODES]
