export const DOCUMENT_REASON_CODES = {
  CR_EXPIRED: 'DOCUMENT_CR_EXPIRED',
  VAT_MISSING: 'DOCUMENT_VAT_MISSING',
  CERTIFICATE_EXPIRED: 'DOCUMENT_CERTIFICATE_EXPIRED',
  LICENSE_MISSING: 'DOCUMENT_LICENSE_MISSING',
  INSURANCE_MISSING: 'DOCUMENT_INSURANCE_MISSING',
  ZAKAT_CERTIFICATE_MISSING: 'DOCUMENT_ZAKAT_CERTIFICATE_MISSING',
} as const

export type DocumentReasonCode =
  (typeof DOCUMENT_REASON_CODES)[keyof typeof DOCUMENT_REASON_CODES]
