export const KNOWLEDGE_REASON_CODES = {
  EDUCATIONAL_HINT: 'KNOWLEDGE_EDUCATIONAL_HINT',
  RISK_HINT: 'KNOWLEDGE_RISK_HINT',
  COMPLIANCE_HINT: 'KNOWLEDGE_COMPLIANCE_HINT',
  LIFECYCLE_HINT: 'KNOWLEDGE_LIFECYCLE_HINT',
  FIELD_GUIDANCE: 'KNOWLEDGE_FIELD_GUIDANCE',
} as const

export type KnowledgeReasonCode =
  (typeof KNOWLEDGE_REASON_CODES)[keyof typeof KNOWLEDGE_REASON_CODES]
