export const MATCH_REASON_CODES = {
  SKILL_LOW: 'MATCH_SKILL_LOW',
  LOCATION_LOW: 'MATCH_LOCATION_LOW',
  VALUE_LOW: 'MATCH_VALUE_LOW',
  BUDGET_LOW: 'MATCH_BUDGET_LOW',
  TIMELINE_LOW: 'MATCH_TIMELINE_LOW',
  EXCHANGE_LOW: 'MATCH_EXCHANGE_LOW',
  REPUTATION_LOW: 'MATCH_REPUTATION_LOW',
  SERVICE_OVERLAP_LOW: 'MATCH_SERVICE_OVERLAP_LOW',
  AVAILABILITY_LOW: 'MATCH_AVAILABILITY_LOW',
  CONSTRAINT_BLOCKED: 'MATCH_CONSTRAINT_BLOCKED',
  HARD_GATE_ROLE_INCOMPATIBLE: 'MATCH_HARD_GATE_ROLE_INCOMPATIBLE',
  HARD_GATE_ROLE_MISSING: 'MATCH_HARD_GATE_ROLE_MISSING',
  HARD_GATE_SKILL_MISSING: 'MATCH_HARD_GATE_SKILL_MISSING',
  HARD_GATE_SERVICE_OVERLAP_LOW: 'MATCH_HARD_GATE_SERVICE_OVERLAP_LOW',
  BELOW_THRESHOLD: 'MATCH_BELOW_THRESHOLD',
  TARGET_ROLE_REQUIRED: 'TARGET_ROLE_REQUIRED',
  TIER_TOP: 'MATCH_TIER_TOP',
  TIER_GOOD: 'MATCH_TIER_GOOD',
  TIER_POSSIBLE: 'MATCH_TIER_POSSIBLE',
  SCORE_SUMMARY: 'MATCH_SCORE_SUMMARY',
  TOPOLOGY_ONE_WAY: 'MATCH_TOPOLOGY_ONE_WAY',
  TOPOLOGY_TWO_WAY: 'MATCH_TOPOLOGY_TWO_WAY',
  TOPOLOGY_CONSORTIUM: 'MATCH_TOPOLOGY_CONSORTIUM',
  TOPOLOGY_CIRCULAR: 'MATCH_TOPOLOGY_CIRCULAR',
} as const

export type MatchReasonCode =
  (typeof MATCH_REASON_CODES)[keyof typeof MATCH_REASON_CODES]
