export const MATCH_REASON_CODES = {
  SKILL_LOW: 'MATCH_SKILL_LOW',
  LOCATION_LOW: 'MATCH_LOCATION_LOW',
  VALUE_LOW: 'MATCH_VALUE_LOW',
  AVAILABILITY_LOW: 'MATCH_AVAILABILITY_LOW',
  CONSTRAINT_BLOCKED: 'MATCH_CONSTRAINT_BLOCKED',
} as const

export type MatchReasonCode =
  (typeof MATCH_REASON_CODES)[keyof typeof MATCH_REASON_CODES]
