export const NEGOTIATION_REASON_CODES = {
  PRICE_GAP: 'NEGOTIATION_PRICE_GAP',
  RESPONSE_DELAY: 'NEGOTIATION_RESPONSE_DELAY',
  TERMS_MISMATCH: 'NEGOTIATION_TERMS_MISMATCH',
  COUNTER_OFFER_PENDING: 'NEGOTIATION_COUNTER_OFFER_PENDING',
} as const

export type NegotiationReasonCode =
  (typeof NEGOTIATION_REASON_CODES)[keyof typeof NEGOTIATION_REASON_CODES]
