export const NEGOTIATION_REASON_CODES = {
  PRICE_GAP: 'NEGOTIATION_PRICE_GAP',
  RESPONSE_DELAY: 'NEGOTIATION_RESPONSE_DELAY',
  TERMS_MISMATCH: 'NEGOTIATION_TERMS_MISMATCH',
  COUNTER_PENDING: 'NEGOTIATION_COUNTER_PENDING',
  /** @deprecated Use COUNTER_PENDING — retained for backward compatibility */
  COUNTER_OFFER_PENDING: 'NEGOTIATION_COUNTER_PENDING',
  STATUS_ACTIVE: 'NEGOTIATION_STATUS_ACTIVE',
  STATUS_COUNTERED: 'NEGOTIATION_STATUS_COUNTERED',
  STATUS_AGREED: 'NEGOTIATION_STATUS_AGREED',
  STATUS_EXPIRED: 'NEGOTIATION_STATUS_EXPIRED',
  STATUS_CANCELLED: 'NEGOTIATION_STATUS_CANCELLED',
  CHANGES_REQUESTED: 'NEGOTIATION_CHANGES_REQUESTED',
  OFFER_ACCEPTED: 'NEGOTIATION_OFFER_ACCEPTED',
  NO_OFFERS: 'NEGOTIATION_NO_OFFERS',
  SCORE_SUMMARY: 'NEGOTIATION_SCORE_SUMMARY',
} as const

export type NegotiationReasonCode =
  (typeof NEGOTIATION_REASON_CODES)[keyof typeof NEGOTIATION_REASON_CODES]
