export const PROFILE_REASON_CODES = {
  MISSING_PHONE: 'PROFILE_MISSING_PHONE',
  MISSING_SKILLS: 'PROFILE_MISSING_SKILLS',
  MISSING_ADDRESS: 'PROFILE_MISSING_ADDRESS',
  MISSING_AVATAR: 'PROFILE_MISSING_AVATAR',
  INCOMPLETE_VERIFICATION: 'PROFILE_INCOMPLETE_VERIFICATION',
  MISSING_EXPERIENCE: 'PROFILE_MISSING_EXPERIENCE',
  MISSING_CERTIFICATIONS: 'PROFILE_MISSING_CERTIFICATIONS',
} as const

export type ProfileReasonCode =
  | (typeof PROFILE_REASON_CODES)[keyof typeof PROFILE_REASON_CODES]
  | `PROFILE_MISSING_${string}`
