export const PROFILE_REASON_CODES = {
  MISSING_FULL_NAME: 'PROFILE_MISSING_FULL_NAME',
  MISSING_ROLE: 'PROFILE_MISSING_ROLE',
  MISSING_SKILLS: 'PROFILE_MISSING_SKILLS',
  MISSING_SERVICES: 'PROFILE_MISSING_SERVICES',
  MISSING_LOCATION: 'PROFILE_MISSING_LOCATION',
  MISSING_AVAILABILITY: 'PROFILE_MISSING_AVAILABILITY',
  MISSING_PORTFOLIO: 'PROFILE_MISSING_PORTFOLIO',
  MISSING_EXPERIENCE: 'PROFILE_MISSING_EXPERIENCE',
  MISSING_CERTIFICATIONS: 'PROFILE_MISSING_CERTIFICATIONS',
  MISSING_PREVIOUS_PROJECTS: 'PROFILE_MISSING_PREVIOUS_PROJECTS',
  MISSING_COMPANY_NAME: 'PROFILE_MISSING_COMPANY_NAME',
  MISSING_BUSINESS_CATEGORY: 'PROFILE_MISSING_BUSINESS_CATEGORY',
  MISSING_PROJECT_CATEGORIES: 'PROFILE_MISSING_PROJECT_CATEGORIES',
  MISSING_CONTACT_PERSON: 'PROFILE_MISSING_CONTACT_PERSON',
  MISSING_TEAM_SIZE: 'PROFILE_MISSING_TEAM_SIZE',
  MISSING_COVERAGE_AREAS: 'PROFILE_MISSING_COVERAGE_AREAS',
  MISSING_FINANCIAL_CAPACITY: 'PROFILE_MISSING_FINANCIAL_CAPACITY',
  MISSING_PHONE: 'PROFILE_MISSING_PHONE',
  MISSING_ADDRESS: 'PROFILE_MISSING_ADDRESS',
  MISSING_AVATAR: 'PROFILE_MISSING_AVATAR',
  INCOMPLETE_VERIFICATION: 'PROFILE_INCOMPLETE_VERIFICATION',
  COMPLETION_LOCKED: 'PROFILE_COMPLETION_LOCKED',
  REQUIRED_COMPLETE: 'PROFILE_REQUIRED_COMPLETE',
  RECOMMENDED_COMPLETE: 'PROFILE_RECOMMENDED_COMPLETE',
  COMPLETE: 'PROFILE_COMPLETE',
  SCORE_SUMMARY: 'PROFILE_SCORE_SUMMARY',
} as const

export type ProfileReasonCode =
  | (typeof PROFILE_REASON_CODES)[keyof typeof PROFILE_REASON_CODES]
  | `PROFILE_MISSING_${string}`
