export const READINESS_REASON_CODES = {
  MISSING_TITLE: 'READINESS_MISSING_TITLE',
  MISSING_INTENT: 'READINESS_MISSING_INTENT',
  MISSING_CATEGORY_PROFESSION: 'READINESS_MISSING_CATEGORY_PROFESSION',
  MISSING_ROLE_INTENT: 'READINESS_MISSING_ROLE_INTENT',
  MISSING_SKILLS_INTENT: 'READINESS_MISSING_SKILLS_INTENT',
  MISSING_SERVICES_INTENT: 'READINESS_MISSING_SERVICES_INTENT',
  MISSING_LOCATION: 'READINESS_MISSING_LOCATION',
  MISSING_TIMELINE: 'READINESS_MISSING_TIMELINE',
  MISSING_COLLABORATION_MODEL: 'READINESS_MISSING_COLLABORATION_MODEL',
  MISSING_DESCRIPTION_SCOPE: 'READINESS_MISSING_DESCRIPTION_SCOPE',
  MISSING_BUDGET: 'READINESS_MISSING_BUDGET',
  MISSING_BUDGET_VALUE_TERMS: 'READINESS_MISSING_BUDGET_VALUE_TERMS',
  MISSING_PREFERRED_PARTNER_TYPE: 'READINESS_MISSING_PREFERRED_PARTNER_TYPE',
  MISSING_ATTACHMENTS: 'READINESS_MISSING_ATTACHMENTS',
  MISSING_COMPLIANCE: 'READINESS_MISSING_COMPLIANCE',
  MISSING_DELIVERY_MILESTONES: 'READINESS_MISSING_DELIVERY_MILESTONES',
  MISSING_SCOPE: 'READINESS_MISSING_SCOPE',
  PUBLISH_BLOCKED: 'READINESS_PUBLISH_BLOCKED',
  PUBLISH_READY: 'READINESS_PUBLISH_READY',
  REQUIRED_COMPLETE: 'READINESS_REQUIRED_COMPLETE',
  RECOMMENDED_COMPLETE: 'READINESS_RECOMMENDED_COMPLETE',
  SCORE_SUMMARY: 'READINESS_SCORE_SUMMARY',
  RECOMMENDED_GAPS: 'READINESS_RECOMMENDED_GAPS',
  COMPLETE: 'READINESS_COMPLETE',
} as const

export type ReadinessReasonCode =
  | (typeof READINESS_REASON_CODES)[keyof typeof READINESS_REASON_CODES]
  | `READINESS_MISSING_${string}`
  | `READINESS_COMPLETE_${string}`
