export const READINESS_REASON_CODES = {
  MISSING_BUDGET: 'READINESS_MISSING_BUDGET',
  MISSING_TIMELINE: 'READINESS_MISSING_TIMELINE',
  MISSING_SCOPE: 'READINESS_MISSING_SCOPE',
  PUBLISH_BLOCKED: 'READINESS_PUBLISH_BLOCKED',
  SCORE_SUMMARY: 'READINESS_SCORE_SUMMARY',
  RECOMMENDED_GAPS: 'READINESS_RECOMMENDED_GAPS',
} as const

export type ReadinessReasonCode =
  | (typeof READINESS_REASON_CODES)[keyof typeof READINESS_REASON_CODES]
  | `READINESS_MISSING_${string}`
  | `READINESS_COMPLETE_${string}`
