export const VETTING_REASON_CODES = {
  BACKGROUND_PENDING: 'VETTING_BACKGROUND_PENDING',
  REFERENCE_INCOMPLETE: 'VETTING_REFERENCE_INCOMPLETE',
  CREDENTIALS_UNVERIFIED: 'VETTING_CREDENTIALS_UNVERIFIED',
  SANCTIONS_CHECK_PENDING: 'VETTING_SANCTIONS_CHECK_PENDING',
  ACTIVE: 'VETTING_ACTIVE',
  DOCUMENTS_COMPLETE: 'VETTING_DOCUMENTS_COMPLETE',
  REVIEW_PENDING: 'VETTING_REVIEW_PENDING',
  REVIEW_NOT_STARTED: 'VETTING_REVIEW_NOT_STARTED',
  REVIEW_IN_PROGRESS: 'VETTING_REVIEW_IN_PROGRESS',
  REVIEW_CHANGES_REQUESTED: 'VETTING_REVIEW_CHANGES_REQUESTED',
  REVIEW_APPROVED: 'VETTING_REVIEW_APPROVED',
  COMPLETE: 'VETTING_COMPLETE',
  SCORE_SUMMARY: 'VETTING_SCORE_SUMMARY',
} as const

export type VettingReasonCode =
  (typeof VETTING_REASON_CODES)[keyof typeof VETTING_REASON_CODES]
