export const VETTING_REASON_CODES = {
  BACKGROUND_PENDING: 'VETTING_BACKGROUND_PENDING',
  REFERENCE_INCOMPLETE: 'VETTING_REFERENCE_INCOMPLETE',
  CREDENTIALS_UNVERIFIED: 'VETTING_CREDENTIALS_UNVERIFIED',
  SANCTIONS_CHECK_PENDING: 'VETTING_SANCTIONS_CHECK_PENDING',
} as const

export type VettingReasonCode =
  (typeof VETTING_REASON_CODES)[keyof typeof VETTING_REASON_CODES]
