import type { WorkflowDefinition } from '../types.ts'

const MARKETPLACE_COMMANDS = [
  'PublishOpportunity',
  'AcceptPostMatch',
  'DeclinePostMatch',
  'StartNegotiationFromPostMatch',
  'AgreeNegotiation',
  'CancelNegotiation',
  'CreateCommercialAgreementFromPostMatch',
  'CreateCommercialAgreementFromNegotiation',
  'AwardCommercialAgreement',
  'RouteContractDecision',
  'CreateContractFromCommercialAgreement',
  'SignContract',
  'CompleteContract',
] as const

export const MARKETPLACE_WORKFLOW: WorkflowDefinition = {
  key: 'marketplace',
  label: 'Marketplace collaboration',
  startEntity: 'opportunity',
  steps: [
    'opportunity',
    'publish',
    'matching',
    'post_match',
    'negotiation',
    'commercial_agreement',
    'contract',
    'completion',
  ],
  allowedTransitions: [
    { from: 'opportunity', to: 'publish', action: 'publish_opportunity', commandType: 'PublishOpportunity' },
    { from: 'post_match', to: 'negotiation', action: 'start_negotiation_from_post_match', commandType: 'StartNegotiationFromPostMatch' },
    { from: 'post_match', to: 'post_match', action: 'accept_match', commandType: 'AcceptPostMatch' },
    { from: 'post_match', to: 'post_match', action: 'decline_match', commandType: 'DeclinePostMatch' },
    { from: 'negotiation', to: 'commercial_agreement', action: 'agree_negotiation', commandType: 'AgreeNegotiation' },
    { from: 'negotiation', to: 'commercial_agreement', action: 'create_commercial_agreement_from_post_match', commandType: 'CreateCommercialAgreementFromPostMatch' },
    { from: 'negotiation', to: 'commercial_agreement', action: 'create_commercial_agreement_from_negotiation', commandType: 'CreateCommercialAgreementFromNegotiation' },
    { from: 'commercial_agreement', to: 'contract', action: 'award_commercial_agreement', commandType: 'AwardCommercialAgreement' },
    { from: 'commercial_agreement', to: 'commercial_agreement', action: 'route_contract_decision', commandType: 'RouteContractDecision' },
    { from: 'commercial_agreement', to: 'contract', action: 'create_contract_from_commercial_agreement', commandType: 'CreateContractFromCommercialAgreement' },
    { from: 'contract', to: 'completion', action: 'sign_contract', commandType: 'SignContract' },
    { from: 'contract', to: 'completion', action: 'complete_contract', commandType: 'CompleteContract' },
  ],
  allowedCommands: [...MARKETPLACE_COMMANDS],
  businessRules: [
    'PostMatch must be confirmed before starting negotiation',
    'Negotiation must be agreed before creating a commercial agreement',
    'Commercial agreement contract route must pass decision engine approval',
    'Commercial agreement must exist before creating a contract',
    'Collaboration taxonomy must be valid before publish',
  ],
  terminalStates: ['completed', 'cancelled', 'closed', 'terminated'],
}
