export {
  PROFILE_SCHEMA_VERSION,
  assertValidProfile,
  normalizeLegacyProfile,
  toMatchingProfileSnapshot,
  toPublicProfile,
  validateProfile,
} from './src/index.ts'

export type {
  CanonicalProfile,
  CanonicalProfileBase,
  CompanyProfile,
  ContactChannel,
  ContactVisibility,
  CredentialStatus,
  EngagementMode,
  IndividualProfile,
  LegacyNormalizationResult,
  LocalizedText,
  MatchingPreferences,
  MatchingProfileSnapshot,
  PortfolioItem,
  ProficiencyLevel,
  ProfileAvailability,
  ProfileContact,
  ProfileCredential,
  ProfileExperience,
  ProfileKind,
  ProfileLocale,
  ProfileLocation,
  ProfileSchemaVersion,
  ProfileService,
  ProfileSocialLinks,
  ProfileValidationCode,
  ProfileValidationIssue,
  ProfileValidationResult,
  PublicProfile,
  PublicProfileService,
  SocialPlatform,
} from './src/index.ts'
