export const VAL_CODES = {
  FIELD_TITLE_REQUIRED: 'VAL_FIELD_TITLE_REQUIRED',
  FIELD_TITLE_TOO_LONG: 'VAL_FIELD_TITLE_TOO_LONG',
  FIELD_DESCRIPTION_TOO_LONG: 'VAL_FIELD_DESCRIPTION_TOO_LONG',
  FIELD_POSITIVE_NUMBER: 'VAL_FIELD_POSITIVE_NUMBER',
  FIELD_PERCENT_RANGE: 'VAL_FIELD_PERCENT_RANGE',
  FIELD_ARRAY_EMPTY: 'VAL_FIELD_ARRAY_EMPTY',

  DATE_START_IN_PAST: 'VAL_DATE_START_IN_PAST',
  DATE_END_BEFORE_START: 'VAL_DATE_END_BEFORE_START',
  DATE_DURATION_INVALID: 'VAL_DATE_DURATION_INVALID',
  DATE_DELIVERY_AFTER_END: 'VAL_DATE_DELIVERY_AFTER_END',
  DATE_START_SOON: 'VAL_DATE_START_SOON',
  DATE_DEADLINE_IN_PAST: 'VAL_DATE_DEADLINE_IN_PAST',
  DATE_AVAILABILITY_END_IN_PAST: 'VAL_DATE_AVAILABILITY_END_IN_PAST',
  DATE_DEADLINE_BEFORE_START: 'VAL_DATE_DEADLINE_BEFORE_START',
  DATE_AVAILABILITY_END_BEFORE_START: 'VAL_DATE_AVAILABILITY_END_BEFORE_START',

  BUDGET_CASH_REQUIRED: 'VAL_BUDGET_CASH_REQUIRED',
  BUDGET_BELOW_MINIMUM: 'VAL_BUDGET_BELOW_MINIMUM',
  BUDGET_PROFIT_FIELDS_REQUIRED: 'VAL_BUDGET_PROFIT_FIELDS_REQUIRED',
  BUDGET_EQUITY_FIELDS_REQUIRED: 'VAL_BUDGET_EQUITY_FIELDS_REQUIRED',
  BUDGET_HYBRID_COMPONENT_REQUIRED: 'VAL_BUDGET_HYBRID_COMPONENT_REQUIRED',

  SKILL_REQUIRED_MISSING: 'VAL_SKILL_REQUIRED_MISSING',
  SKILL_PROVIDED_MISSING: 'VAL_SKILL_PROVIDED_MISSING',
  SKILL_DUPLICATE: 'VAL_SKILL_DUPLICATE',
  SKILL_YEARS_NEGATIVE: 'VAL_SKILL_YEARS_NEGATIVE',
  SKILL_LEVEL_YEARS_IMPOSSIBLE: 'VAL_SKILL_LEVEL_YEARS_IMPOSSIBLE',

  PACKAGE_TITLE_REQUIRED: 'VAL_PACKAGE_TITLE_REQUIRED',
  PACKAGE_DESCRIPTION_REQUIRED: 'VAL_PACKAGE_DESCRIPTION_REQUIRED',
  PACKAGE_SKILL_REQUIRED: 'VAL_PACKAGE_SKILL_REQUIRED',
  PACKAGE_DEADLINE_REQUIRED: 'VAL_PACKAGE_DEADLINE_REQUIRED',
  PACKAGE_DEADLINE_AFTER_PROJECT: 'VAL_PACKAGE_DEADLINE_AFTER_PROJECT',
  PACKAGE_DUPLICATE_NAME: 'VAL_PACKAGE_DUPLICATE_NAME',
  PACKAGE_COUNT_EXCEEDED: 'VAL_PACKAGE_COUNT_EXCEEDED',

  COMMERCIAL_RETENTION_RANGE: 'VAL_COMMERCIAL_RETENTION_RANGE',
  COMMERCIAL_PROFIT_SHARE_RANGE: 'VAL_COMMERCIAL_PROFIT_SHARE_RANGE',
  COMMERCIAL_VAT_RANGE: 'VAL_COMMERCIAL_VAT_RANGE',
  COMMERCIAL_ADVANCE_EXCEEDS_BUDGET: 'VAL_COMMERCIAL_ADVANCE_EXCEEDS_BUDGET',
  COMMERCIAL_MIN_MAX_CONTRACT: 'VAL_COMMERCIAL_MIN_MAX_CONTRACT',

  CAPACITY_REQUIRED_INVALID: 'VAL_CAPACITY_REQUIRED_INVALID',
  CAPACITY_AVAILABLE_INVALID: 'VAL_CAPACITY_AVAILABLE_INVALID',
  CAPACITY_NEGATIVE: 'VAL_CAPACITY_NEGATIVE',

  DOC_CR_REQUIRED: 'VAL_DOC_CR_REQUIRED',
  DOC_INSURANCE_REQUIRED: 'VAL_DOC_INSURANCE_REQUIRED',
  DOC_PERFORMANCE_BOND_REQUIRED: 'VAL_DOC_PERFORMANCE_BOND_REQUIRED',
  DOC_EXPIRED: 'VAL_DOC_EXPIRED',

  LOCATION_INCONSISTENT: 'VAL_LOCATION_INCONSISTENT',
  LOCATION_ONSITE_REQUIRED: 'VAL_LOCATION_ONSITE_REQUIRED',

  DUP_SIMILAR_DRAFT: 'VAL_DUP_SIMILAR_DRAFT',

  INTENT_NEED_HAS_AVAILABLE_CAPACITY: 'VAL_INTENT_NEED_HAS_AVAILABLE_CAPACITY',
  INTENT_NEED_HAS_PRICING_TABLE: 'VAL_INTENT_NEED_HAS_PRICING_TABLE',
  INTENT_OFFER_HAS_REQUIRED_CAPACITY: 'VAL_INTENT_OFFER_HAS_REQUIRED_CAPACITY',
  INTENT_OFFER_HAS_MANDATORY_DEADLINE: 'VAL_INTENT_OFFER_HAS_MANDATORY_DEADLINE',
  INTENT_OFFER_REQUIRED_BUDGET_NON_CASH: 'VAL_INTENT_OFFER_REQUIRED_BUDGET_NON_CASH',

  TAXONOMY_INVALID: 'VAL_TAXONOMY_INVALID',

  PUBLISH_PROFILE_INCOMPLETE: 'VAL_PUBLISH_PROFILE_INCOMPLETE',
  PUBLISH_VETTING_NOT_APPROVED: 'VAL_PUBLISH_VETTING_NOT_APPROVED',
  PUBLISH_READINESS_BELOW_THRESHOLD: 'VAL_PUBLISH_READINESS_BELOW_THRESHOLD',
  PUBLISH_FIELD_ERRORS: 'VAL_PUBLISH_FIELD_ERRORS',
  PUBLISH_BUSINESS_ERRORS: 'VAL_PUBLISH_BUSINESS_ERRORS',
} as const

export type ValCode = (typeof VAL_CODES)[keyof typeof VAL_CODES]
